name: Update DEB-PKG

on:
  schedule:
    - cron: '0 12 4,8,12,16,20,24,28 * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
        env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Check update
        run: |
          sudo apt install reprepro -y
          bash update.sh
          git push